let btn = document.querySelector('#new-quote');

let quote = document.querySelector('.quote');

let person = document.querySelector('.person');

const quotes = [
    { quote: `The only way to do great work is to love what you do.`, person: `Steve Jobs` },
    { quote: `In the middle of every difficulty lies opportunity.`, person: `Albert Einstein` },
    { quote: `Life is what happens when you're busy making other plans.`, person: `John Lennon` },
    { quote: `Believe you can and you're halfway there.`, person: `Theodore Roosevelt` },
    { quote: `The only limit to our realization of tomorrow will be our doubts of today.`, person: `Franklin D. Roosevelt` },
    { quote: `The best way to predict the future is to create it.`, person: `Peter Drucker` },
    { quote: `The only thing necessary for the triumph of evil is for good men to do nothing.`, person: `Edmund Burke` },
    { quote: `In three words I can sum up everything I've learned about life: It goes on.`, person: `Robert Frost` },
    { quote: `The greatest glory in living lies not in never falling, but in rising every time we fall.`, person: `Nelson Mandela` },
    { quote: `The future belongs to those who believe in the beauty of their dreams.`, person: `Eleanor Roosevelt` },
    { quote: `Your time is limited, don't waste it living someone else's life.`, person: `Steve Jobs` },
    { quote: `Don't count the days, make the days count.`, person: `Muhammad Ali` },
    { quote: `The only person you are destined to become is the person you decide to be.`, person: `Ralph Waldo Emerson` },
    { quote: `It is never too late to be what you might have been.`, person: `George Eliot` },
    { quote: `Success is walking from failure to failure with no loss of enthusiasm.`, person: `Winston Churchill` },
    { quote: `Life is really simple, but we insist on making it complicated.`, person: `Confucius` },
    { quote: `Change your thoughts and you change your world.`, person: `Norman Vincent Peale` },
    { quote: `The only true wisdom is in knowing you know nothing.`, person: `Socrates` },
    { quote: `The journey of a thousand miles begins with one step.`, person: `Lao Tzu` },
    { quote: `To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.`, person: `Ralph Waldo Emerson` },
    { quote: `Imagination is more important than knowledge.`, person: `Albert Einstein` },
    { quote: `Don't let yesterday take up too much of today.`, person: `Will Rogers` },
    { quote: `Life is 10% what happens to us and 90% how we react to it.`, person: `Charles R. Swindoll` },
    { quote: `The only thing we have to fear is fear itself.`, person: `Franklin D. Roosevelt` },
    { quote: `Success is not in what you have, but who you are.`, person: `Bo Bennett` },
    { quote: `In the end, we will remember not the words of our enemies, but the silence of our friends.`, person: `Martin Luther King Jr.` },
    { quote: `The only source of knowledge is experience.`, person: `Albert Einstein` },
    { quote: `To succeed in life, you need two things: ignorance and confidence.`, person: `Mark Twain` },
    { quote: `Life is what happens when you're busy making other plans.`, person: `John Lennon` },
    { quote: `In order to be irreplaceable, one must always be different.`, person: `Coco Chanel` },
    { quote: `The best revenge is massive success.`, person: `Frank Sinatra` },
    { quote: `Life is either a daring adventure or nothing at all.`, person: `Helen Keller` },
    { quote: `The only way to do great work is to love what you do.`, person: `Steve Jobs` },
    { quote: `In the middle of every difficulty lies opportunity.`, person: `Albert Einstein` },
    { quote: `Life is what happens when you're busy making other plans.`, person: `John Lennon` },
    { quote: `Believe you can and you're halfway there.`, person: `Theodore Roosevelt` },
    { quote: `The only limit to our realization of tomorrow will be our doubts of today.`, person: `Franklin D. Roosevelt` },
    { quote: `The best way to predict the future is to create it.`, person: `Peter Drucker` },
    { quote: `The only thing necessary for the triumph of evil is for good men to do nothing.`, person: `Edmund Burke` },
    { quote: `In three words I can sum up everything I've learned about life: It goes on.`, person: `Robert Frost` },
    { quote: `The greatest glory in living lies not in never falling, but in rising every time we fall.`, person: `Nelson Mandela` },
    { quote: `The future belongs to those who believe in the beauty of their dreams.`, person: `Eleanor Roosevelt` },
    { quote: `Your time is limited, don't waste it living someone else's life.`, person: `Steve Jobs` },
    { quote: `Don't count the days, make the days count.`, person: `Muhammad Ali` },
    { quote: `The only person you are destined to become is the person you decide to be.`, person: `Ralph Waldo Emerson` },
    { quote: `It is never too late to be what you might have been.`, person: `George Eliot` },
    { quote: `Success is walking from failure to failure with no loss of enthusiasm.`, person: `Winston Churchill` },
    { quote: `Life is really simple, but we insist on making it complicated.`, person: `Confucius` },
    { quote: `Change your thoughts and you change your world.`, person: `Norman Vincent Peale` },
    { quote: `The only true wisdom is in knowing you know nothing.`, person: `Socrates` },
    { quote: `The journey of a thousand miles begins with one step.`, person: `Lao Tzu` },
    { quote: `To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.`, person: `Ralph Waldo Emerson` },
    { quote: `Imagination is more important than knowledge.`, person: `Albert Einstein` },
    { quote: `Don't let yesterday take up too much of today.`, person: `Will Rogers` },
    { quote: `Life is 10% what happens to us and 90% how we react to it.`, person: `Charles R. Swindoll` },
    { quote: `The only thing we have to fear is fear itself.`, person: `Franklin D. Roosevelt` },
    { quote: `Success is not in what you have, but who you are.`, person: `Bo Bennett` },
    { quote: `In the end, we will remember not the words of our enemies, but the silence of our friends.`, person: `Martin Luther King Jr.` },
    { quote: `The only source of knowledge is experience.`, person: `Albert Einstein` },
    { quote: `To succeed in life, you need two things: ignorance and confidence.`, person: `Mark Twain` },
    { quote: `Life is what happens when you're busy making other plans.`, person: `John Lennon` },
    { quote: `In order to be irreplaceable, one must always be different.`, person: `Coco Chanel` },
    { quote: `The best revenge is massive success.`, person: `Frank Sinatra` },
    { quote: `Life is either a daring adventure or nothing at all.`, person: `Helen Keller` },
    { quote: `The only way to do great work is to love what you do.`, person: `Steve Jobs` },
    { quote: `The journey of a thousand miles begins with one step.`, person: `Lao Tzu` },
    { quote: `Don't count the days, make the days count.`, person: `Muhammad Ali` },
    { quote: `The only limit to our realization of tomorrow will be our doubts of today.`, person: `Franklin D. Roosevelt` },
    { quote: `The best way to predict the future is to create it.`, person: `Peter Drucker` },
    { quote: `Life is what happens when you're busy making other plans.`, person: `John Lennon` },
    { quote: `Change your thoughts and you change your world.`, person: `Norman Vincent Peale` },
    { quote: `Imagination is more important than knowledge.`, person: `Albert Einstein` },
    { quote: `In three words I can sum up everything I've learned about life: It goes on.`, person: `Robert Frost` },
    { quote: `To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.`, person: `Ralph Waldo Emerson` },
    { quote: `The only person you are destined to become is the person you decide to be.`, person: `Ralph Waldo Emerson` },
    { quote: `It is never too late to be what you might have been.`, person: `George Eliot` },
    { quote: `The greatest glory in living lies not in never falling, but in rising every time we fall.`, person: `Nelson Mandela` },
    { quote: `Your time is limited, don't waste it living someone else's life.`, person: `Steve Jobs` },
    { quote: `Success is walking from failure to failure with no loss of enthusiasm.`, person: `Winston Churchill` },
    { quote: `The future belongs to those who believe in the beauty of their dreams.`, person: `Eleanor Roosevelt` },
    { quote: `The only thing necessary for the triumph of evil is for good men to do nothing.`, person: `Edmund Burke` },
    { quote: `The only true wisdom is in knowing you know nothing.`, person: `Socrates` },
    { quote: `Don't let yesterday take up too much of today.`, person: `Will Rogers` },
    { quote: `Life is 10% what happens to us and 90% how we react to it.`, person: `Charles R. Swindoll` },
    { quote: `The only thing we have to fear is fear itself.`, person: `Franklin D. Roosevelt` },
    { quote: `Success is not in what you have, but who you are.`, person: `Bo Bennett` },
    { quote: `In the end, we will remember not the words of our enemies, but the silence of our friends.`, person: `Martin Luther King Jr.` },
    { quote: `The only source of knowledge is experience.`, person: `Albert Einstein` },
    { quote: `To succeed in life, you need two things: ignorance and confidence.`, person: `Mark Twain` },
    { quote: `Life is what happens when you're busy making other plans.`, person: `John Lennon` },
    { quote: `In order to be irreplaceable, one must always be different.`, person: `Coco Chanel` },
    { quote: `The best revenge is massive success.`, person: `Frank Sinatra` },
    { quote: `Life is either a daring adventure or nothing at all.`, person: `Helen Keller` },

];

btn.addEventListener('click', function (e) {
    // Math.random can also generate decimal number so, Math.floor is used to round down
    console.log(e.target.getAttribute('id') + " is clicked");
    let random = Math.floor(Math.random() * quotes.length);

    quote.innerText = quotes[random].quote;
    person.innerText = quotes[random].person;

})